// components/CRM/RFQ/constants.ts

import type { RFQItem, CountryMetric } from './types';

export const INITIAL_RFQS: RFQItem[] = [
  {
    id: 'rfq1',
    rfqNumber: '260916-1',
    company: 'NGEN IT PTE. LTD.',
    country: 'Singapore',
    date: '16 Sep 2026',
    time: '06:40 PM',
    agingDays: 2,
    stage: 'pending',
    source: 'online',
    salesman: 'Nahid Hasan',
    assignedTo: 'Already Registered Client',
    clientInfo: {
      contactName: 'ADAN MAHMUD',
      email: 'sales@ngenitltd.com',
      phone: '01714243446',
      company: 'NGEN IT PTE. LTD.',
      country: 'Singapore',
      zipCode: '079903',
      tentativeBudget: '—',
      purchaseDate: '—',
    },
    products: [
      {
        name: 'Acronis Access — subscription license renewal (1 year) — 1 user',
        qty: 2,
        spec: 'Enterprise Access Subscription renewal with 12 months standard SLA support',
      },
    ],
  },
  {
    id: 'rfq2',
    rfqNumber: '260907-1',
    company: 'Everyonic Technology',
    country: 'Pakistan',
    date: '07 Sep 2026',
    time: '03:55 PM',
    agingDays: 12,
    stage: 'pending',
    source: 'online',
    salesman: 'Akramul',
    assignedTo: 'Unassigned',
    clientInfo: {
      contactName: 'Tariq Mehmood',
      email: 'tariq@everyonic.pk',
      phone: '+92 300 1234567',
      company: 'Everyonic Technology',
      country: 'Pakistan',
      zipCode: '54000',
      tentativeBudget: '$4,200',
      purchaseDate: '28 Sep 2026',
    },
    products: [
      {
        name: 'Industrial Ethernet Switch 16-Port Managed',
        qty: 4,
        spec: 'Ruggedized DIN-rail switch, dual power input',
      },
    ],
  },
  {
    id: 'rfq3',
    rfqNumber: '260903-1',
    company: 'MAV SZK Zrt.',
    country: 'Hungary',
    date: '03 Sep 2026',
    time: '12:26 PM',
    agingDays: 16,
    stage: 'quoted',
    source: 'online',
    salesman: 'Nahid Hasan',
    assignedTo: 'Nahid Hasan',
    clientInfo: {
      contactName: 'Zoltán Kovács',
      email: 'kovacs.z@mavszk.hu',
      phone: '+36 1 456 7890',
      company: 'MAV SZK Zrt.',
      country: 'Hungary',
      zipCode: '1087',
      tentativeBudget: '€8,500',
      purchaseDate: '15 Oct 2026',
    },
    products: [
      {
        name: 'Balluff Inductive Sensors Pack BES M18',
        qty: 12,
        spec: 'M18x1 shielded inductive proximity switches',
      },
    ],
  },
  {
    id: 'rfq4',
    rfqNumber: '260902-1',
    company: 'NGEN IT',
    country: 'Bangladesh',
    date: '02 Sep 2026',
    time: '03:01 PM',
    agingDays: 17,
    stage: 'quoted',
    source: 'online',
    salesman: 'Akramul',
    assignedTo: 'Akramul',
    clientInfo: {
      contactName: 'Kazi Farhan',
      email: 'farhan.k@ngenit.com',
      phone: '01819223344',
      company: 'NGEN IT',
      country: 'Bangladesh',
      zipCode: '1212',
      tentativeBudget: '৳5,50,000',
      purchaseDate: '20 Sep 2026',
    },
    products: [
      {
        name: 'Fortinet FortiGate 60F Firewall & UTM Bundle',
        qty: 1,
        spec: '1-Year 24x7 FortiCare and FortiGuard Unified Threat Protection',
      },
    ],
  },
  {
    id: 'rfq5',
    rfqNumber: '260901-1',
    company: 'O3 Capital Finance Company Limited',
    country: 'Nigeria',
    date: '01 Sep 2026',
    time: '09:00 PM',
    agingDays: 17,
    stage: 'pending',
    source: 'online',
    salesman: 'CRM Manager, ME',
    assignedTo: 'CRM Manager, ME',
    clientInfo: {
      contactName: 'Babatunde Adeleke',
      email: 'badeleke@o3capitalng.com',
      phone: '+234 1 270 1234',
      company: 'O3 Capital Finance Company Limited',
      country: 'Nigeria',
      zipCode: '101233',
      tentativeBudget: '$12,000',
      purchaseDate: '30 Sep 2026',
    },
    products: [
      {
        name: 'Radmin Server & Viewer Perpetual Licenses (50 Pack)',
        qty: 2,
        spec: 'Commercial enterprise bulk license key',
      },
    ],
  },
  {
    id: 'rfqA1',
    rfqNumber: '260812-1',
    company: 'Meridian Port Authority',
    country: 'United States of America',
    date: '12 Aug 2026',
    time: '10:15 AM',
    agingDays: 45,
    stage: 'archived',
    source: 'online',
    salesman: 'CRM Manager, ME',
    assignedTo: 'Archived Record',
    clientInfo: {
      contactName: 'Robert Vance',
      email: 'rvance@meridianport.gov',
      phone: '+1 206 555 0192',
      company: 'Meridian Port Authority',
      country: 'United States of America',
      zipCode: '98101',
      tentativeBudget: '$22,500',
      purchaseDate: '—',
    },
    products: [
      {
        name: 'Zebra RFID Fixed Readers & Antennas',
        qty: 6,
        spec: 'FX9600 4-Port Long Range Integrated RFID System',
      },
    ],
  },
  {
    id: 'rfqA2',
    rfqNumber: '260805-1',
    company: 'Ganges Freight Pvt. Ltd.',
    country: 'India',
    date: '05 Aug 2026',
    time: '04:30 PM',
    agingDays: 52,
    stage: 'archived',
    source: 'online',
    salesman: 'Akramul',
    assignedTo: 'Archived Record',
    clientInfo: {
      contactName: 'Anil Deshmukh',
      email: 'anil@gangesfreight.in',
      phone: '+91 22 2345 6789',
      company: 'Ganges Freight Pvt. Ltd.',
      country: 'India',
      zipCode: '400001',
      tentativeBudget: '₹4,50,000',
      purchaseDate: '—',
    },
    products: [
      {
        name: 'Advantech Industrial Gateway Modules',
        qty: 3,
        spec: 'DIN-rail communication gateways',
      },
    ],
  },
  {
    id: 'rfqA3',
    rfqNumber: '260728-1',
    company: 'Delta Steelworks Ltd.',
    country: 'Bangladesh',
    date: '28 Jul 2026',
    time: '11:50 AM',
    agingDays: 60,
    stage: 'archived',
    source: 'online',
    salesman: 'Nahid Hasan',
    assignedTo: 'Archived Record',
    clientInfo: {
      contactName: 'Mustafa Kamal',
      email: 'kamal@deltasteel.com.bd',
      phone: '01711998877',
      company: 'Delta Steelworks Ltd.',
      country: 'Bangladesh',
      zipCode: '1310',
      tentativeBudget: '৳7,80,000',
      purchaseDate: '—',
    },
    products: [
      {
        name: 'Emerson Pressure Sensors & Transmitters',
        qty: 8,
        spec: 'High precision industrial pressure measurement transmitters',
      },
    ],
  },
];

export const COUNTRY_METRICS: CountryMetric[] = [
  { country: 'Bangladesh', count: 15, pct: 54 },
  { country: 'United States of America', count: 5, pct: 18 },
  { country: 'India', count: 5, pct: 18 },
  { country: 'Nigeria', count: 3, pct: 11 },
];